name = "gadeer-co"
type = "javascript"
account_id = ""  # سيتم ملأه من GitHub Secrets
workers_dev = true

[build]
command = "npm run build"
cwd = "./"
watch_paths = ["src/**/*.ts", "src/**/*.tsx"]

[build.upload]
format = "service-worker"