import { activeDocuments, activeTransactions } from "@/lib/customer-trash";
import { readDetails, detailText } from "@/lib/customer-statement";
import { createFileRoute, Link } from "@tanstack/react-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Download, FilePenLine, FileText, Search, Trash2 } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { amount, escapeHtml, printPdf } from "@/lib/print-pdf";

export const Route=createFileRoute("/_authenticated/receipts")({component:ReceiptsPage});

type Receipt={id:string;document_number:string;company_name:string|null;driver_name:string|null;status:string;created_at:string;document_value:number|null;cargo_typedetails:string|null};
type Income={id:string;document_number:string|null;driver_name:string|null;created_at:string;amount:number;description:string|null;cargo_typedetails:string|null;company_id:string};
type Company={id:string;company_name:string};

function ReceiptsPage(){
 const [items,setItems]=useState<Receipt[]>([]),[incomes,setIncomes]=useState<Income[]>([]),[companies,setCompanies]=useState<Company[]>([]),[editing,setEditing]=useState<Receipt|null>(null),[editingIncome,setEditingIncome]=useState<Income|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[message,setMessage]=useState(""),[search,setSearch]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");const [docs,tx,co]=await Promise.all([activeDocuments(supabase).order("created_at",{ascending:false}),activeTransactions(supabase).eq("type","income").order("created_at",{ascending:false}),supabase.from("companies").select("id,company_name")]);const e=docs.error||tx.error||co.error;if(e)setError(e.message);else{setItems((docs.data??[]) as Receipt[]);setIncomes((tx.data??[]) as Income[]);setCompanies((co.data??[]) as Company[])}setLoading(false)},[]);
 useEffect(()=>{void load()},[load]);
 const companyMap=useMemo(()=>new Map(companies.map(x=>[x.id,x.company_name])),[companies]);
 const filteredIncomes=useMemo(()=>{const q=search.trim().toLowerCase();return !q?incomes:incomes.filter(x=>{const d=readDetails(x.description);return [x.document_number||"",x.driver_name||"",companyMap.get(x.company_id)||"",detailText(d.companyName),x.cargo_typedetails||""].some(v=>v.toLowerCase().includes(q))})},[incomes,search,companyMap]);
 async function save(){if(!editing)return;const r=await supabase.from("documents").update({company_name:editing.company_name??undefined,driver_name:editing.driver_name??undefined,status:editing.status,document_value:editing.document_value??undefined,cargo_typedetails:editing.cargo_typedetails??undefined}).eq("id",editing.id);if(r.error)setError(r.error.message);else{setMessage("تم تحديث الوصلة بنجاح.");setEditing(null);await load()}}
 async function saveIncome(){if(!editingIncome)return;const r=await supabase.from("transactions").update({driver_name:editingIncome.driver_name,amount:editingIncome.amount,cargo_typedetails:editingIncome.cargo_typedetails}).eq("id",editingIncome.id).eq("type","income");if(r.error)setError(r.error.message);else{setMessage("تم تحديث وصل الدخل بنجاح.");setEditingIncome(null);await load()}}
 async function remove(x:Receipt){if(!confirm(`حذف الوصلة ${x.document_number}؟`))return;const r=await supabase.from("documents").delete().eq("id",x.id);if(r.error)setError(r.error.message);else{setMessage("تم حذف الوصلة.");await load()}}
 async function removeIncome(x:Income){if(!confirm(`حذف وصل الدخل ${x.document_number||"—"} من المستحقات؟`))return;const r=await supabase.from("transactions").delete().eq("id",x.id).eq("type","income");if(r.error)setError(r.error.message);else{setMessage("تم حذف وصل الدخل.");await load()}}
 function pdf(x:Receipt){printPdf(`وصل رقم ${x.document_number}`,`<h2>بيانات الوصل</h2><table><tr><th>رقم الوصل</th><td>${escapeHtml(x.document_number)}</td></tr><tr><th>الشركة / المشروع</th><td>${escapeHtml(x.company_name||"—")}</td></tr><tr><th>السائق</th><td>${escapeHtml(x.driver_name||"—")}</td></tr><tr><th>تفاصيل الحمولة</th><td>${escapeHtml(x.cargo_typedetails||"—")}</td></tr><tr><th>القيمة</th><td>${amount(x.document_value)} IQD</td></tr></table>`)}
 function incomePdf(x:Income){const d=readDetails(x.description);const company=companyMap.get(x.company_id)||detailText(d.companyName)||"—";printPdf(`وصل دخل رقم ${x.document_number||"—"}`,`<h2>وصل دخل</h2><table><tr><th>رقم الوصل</th><td>${escapeHtml(x.document_number||"—")}</td></tr><tr><th>الشركة</th><td>${escapeHtml(company)}</td></tr><tr><th>السائق</th><td>${escapeHtml(x.driver_name||"—")}</td></tr><tr><th>تفاصيل الحمولة</th><td>${escapeHtml(x.cargo_typedetails||"—")}</td></tr><tr><th>المستحق</th><td>${amount(x.amount)} USD</td></tr></table>`)}
 return <div className="receipts-page" dir="rtl"><style>{`.receipts-page{width:min(1100px,100%);margin:auto;padding:28px 14px 100px;color:var(--gh-text,#17233f)}.hero{display:flex;justify-content:space-between;align-items:center;margin-bottom:20px}.hero h1{margin:0}.hero p{color:var(--gh-muted)}.panel{background:var(--gh-panel,#fff);border:1px solid var(--gh-line,#d9dfeb);border-radius:22px;padding:20px;margin-bottom:16px}.panel-head{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:14px}.panel-head h2{margin:0}.search{position:relative;min-width:250px}.search svg{position:absolute;right:11px;top:11px;color:var(--gh-muted)}.search input{width:100%;padding:10px 36px 10px 10px;border:1px solid var(--gh-line);border-radius:12px;background:transparent;color:inherit}.notice{padding:11px;border-radius:10px;background:#16a34a18;color:#15803d;margin-bottom:12px}.error{background:#dc262618;color:#b91c1c}.list{display:grid;gap:10px}.row{border:1px solid var(--gh-line,#d9dfeb);border-radius:15px;padding:14px;display:flex;justify-content:space-between;gap:12px;align-items:center}.row h3{margin:0}.row p{margin:4px 0;color:var(--gh-muted)}.badge{display:inline-flex;padding:4px 9px;border-radius:999px;background:#c9a14a1c;color:#b28a32;font-size:.76rem;font-weight:900;margin-right:7px}.actions{display:flex;gap:7px;flex-wrap:wrap}.btn{display:inline-flex;align-items:center;gap:6px;border:1px solid #c9a14a;background:#c9a14a;color:#17233f;border-radius:10px;padding:9px 12px;font-weight:800;cursor:pointer}.btn.secondary{background:transparent;color:inherit}.btn.danger{border-color:#dc262655;color:#dc2626;background:transparent}.modal{position:fixed;inset:0;background:#071a3bcc;display:grid;place-items:center;padding:18px;z-index:20}.dialog{width:min(560px,100%);background:var(--gh-panel,#fff);padding:22px;border-radius:20px;display:grid;gap:12px}.dialog input,.dialog select{padding:11px;border:1px solid var(--gh-line);border-radius:10px;background:transparent;color:inherit}@media(max-width:650px){.row,.hero,.panel-head{align-items:flex-start;flex-direction:column}.search{width:100%;min-width:0}}`}</style>
 <header className="hero"><div><h1>إدارة الوصلات</h1><p>عدّل بيانات الوصل، احفظ التغييرات، أو اطبع نسخة PDF رسمية.</p></div><Link to="/" className="btn secondary">لوحة التحكم</Link></header>
 {error&&<div className="notice error">{error}</div>}{message&&<div className="notice">{message}</div>}
 <section className="panel"><div className="panel-head"><div><h2>وصولات الدخل</h2><p>كل حركات الدخل والمستحقات المسجلة تظهر هنا.</p></div><div className="search"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="بحث برقم الوصل، السائق أو الشركة"/></div></div>{loading?<p>جارٍ التحميل...</p>:<div className="list">{filteredIncomes.length===0?<p>لا توجد وصولات دخل.</p>:filteredIncomes.map(x=>{const d=readDetails(x.description),company=companyMap.get(x.company_id)||detailText(d.companyName)||"بدون شركة";return <article className="row" key={x.id}><div><h3><FileText size={17}/> {x.document_number||"—"} <span className="badge">دخل</span></h3><p>{company} · {x.driver_name||"بدون سائق"} · {amount(x.amount)} USD</p></div><div className="actions"><button className="btn secondary" onClick={()=>setEditingIncome({...x})}><FilePenLine size={16}/> تعديل</button><button className="btn secondary" onClick={()=>incomePdf(x)}><Download size={16}/> PDF</button><button className="btn danger" onClick={()=>void removeIncome(x)}><Trash2 size={16}/> حذف</button></div></article>})}</div>}</section>
 <section className="panel"><div className="panel-head"><h2>الوصلات الأخرى</h2></div>{loading?<p>جارٍ التحميل...</p>:<div className="list">{items.length===0?<p>لا توجد وصولات محفوظة.</p>:items.map(x=><article className="row" key={x.id}><div><h3><FileText size={17}/> {x.document_number}</h3><p>{x.company_name||"بدون شركة"} · {x.driver_name||"بدون سائق"} · {amount(x.document_value)} IQD</p></div><div className="actions"><button className="btn secondary" onClick={()=>setEditing({...x})}><FilePenLine size={16}/> تعديل</button><button className="btn secondary" onClick={()=>pdf(x)}><Download size={16}/> PDF</button><button className="btn danger" onClick={()=>void remove(x)}><Trash2 size={16}/> حذف</button></div></article>)}</div>}</section>
 {editing&&<div className="modal"><div className="dialog"><h2>تعديل الوصلة {editing.document_number}</h2><label>الشركة / المشروع<input value={editing.company_name||""} onChange={e=>setEditing({...editing,company_name:e.target.value})}/></label><label>اسم السائق<input value={editing.driver_name||""} onChange={e=>setEditing({...editing,driver_name:e.target.value})}/></label><label>تفاصيل الحمولة<input value={editing.cargo_typedetails||""} onChange={e=>setEditing({...editing,cargo_typedetails:e.target.value})}/></label><label>القيمة<input type="number" min="0" value={editing.document_value??0} onChange={e=>setEditing({...editing,document_value:Number(e.target.value)})}/></label><div className="actions"><button className="btn" onClick={()=>void save()}>حفظ التعديلات</button><button className="btn secondary" onClick={()=>setEditing(null)}>إلغاء</button></div></div></div>}
 {editingIncome&&<div className="modal"><div className="dialog"><h2>تعديل وصل الدخل {editingIncome.document_number||"—"}</h2><label>اسم السائق<input value={editingIncome.driver_name||""} onChange={e=>setEditingIncome({...editingIncome,driver_name:e.target.value})}/></label><label>تفاصيل الحمولة<input value={editingIncome.cargo_typedetails||""} onChange={e=>setEditingIncome({...editingIncome,cargo_typedetails:e.target.value})}/></label><label>المستحق بالدولار<input type="number" min="0" step="0.01" value={editingIncome.amount} onChange={e=>setEditingIncome({...editingIncome,amount:Number(e.target.value)})}/></label><div className="actions"><button className="btn" onClick={()=>void saveIncome()}>حفظ التعديلات</button><button className="btn secondary" onClick={()=>setEditingIncome(null)}>إلغاء</button></div></div></div>}
 </div>
}