import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useState, type ReactNode } from "react";
import { ArrowDownLeft, ArrowUpRight, CalendarDays, FileText, Filter, Gauge, Phone, RefreshCcw, Search, TrendingUp, UserRound, Users, WalletCards } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";

export const Route = createFileRoute("/_authenticated/reports")({
  head: () => ({ meta: [{ title: "تقارير العملاء | لوحة التحكم" }, { name: "description", content: "تقارير مالية تفصيلية لكل عميل مع كامل الحساب وجميع الحركات والإحصائيات." }] }),
  component: ReportsPage,
});

type Trader={id:string;name:string;phone:string|null;address:string|null;notes:string|null;created_at:string};
type Transaction={id:string;trader_id:string|null;company_id:string;document_id:string|null;document_number:string|null;amount:number;type:string;description:string|null;cargo_typedetails:string|null;driver_name:string|null;created_at:string};

type ReportStats={incoming:number;outgoing:number;balance:number;count:number;incomingCount:number;outgoingCount:number;documents:number;average:number;firstDate:string|null;lastDate:string|null};

function ReportsPage(){
  const [traders,setTraders]=useState<Trader[]>([]);const [transactions,setTransactions]=useState<Transaction[]>([]);const [selectedTraderId,setSelectedTraderId]=useState("");const [search,setSearch]=useState("");const [dateFrom,setDateFrom]=useState("");const [dateTo,setDateTo]=useState("");const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);
  useEffect(()=>{void loadReportData()},[]);
  async function loadReportData(){setLoading(true);setError(null);const[{data:tradersData,error:tradersError},{data:transactionsData,error:transactionsError}]=await Promise.all([supabase.from("traders").select("id,name,phone,address,notes,created_at").order("name"),supabase.from("transactions").select("id,trader_id,company_id,document_id,document_number,amount,type,description,cargo_typedetails,driver_name,created_at").order("created_at",{ascending:false})]);if(tradersError||transactionsError){setError(tradersError?.message||transactionsError?.message||"تعذر تحميل بيانات التقارير.");setLoading(false);return}const next=(tradersData??[]) as Trader[];setTraders(next);setTransactions((transactionsData??[]) as Transaction[]);setSelectedTraderId(c=>c||next[0]?.id||"");setLoading(false)}
  const filteredTraders=useMemo(()=>{const q=search.trim().toLowerCase();return q?traders.filter(t=>[t.name,t.phone??"",t.address??""].some(v=>v.toLowerCase().includes(q))):traders},[search,traders]);
  const selectedTrader=traders.find(t=>t.id===selectedTraderId)??null;
  const allTraderTransactions=useMemo(()=>transactions.filter(t=>t.trader_id===selectedTraderId),[transactions,selectedTraderId]);
  const traderTransactions=useMemo(()=>allTraderTransactions.filter(t=>{const d=new Date(t.created_at);if(dateFrom&&d<new Date(`${dateFrom}T00:00:00`))return false;if(dateTo&&d>new Date(`${dateTo}T23:59:59`))return false;return true}),[allTraderTransactions,dateFrom,dateTo]);
  const hasDateFilter=Boolean(dateFrom||dateTo);const stats=useMemo(()=>buildStats(traderTransactions),[traderTransactions]);const allTimeStats=useMemo(()=>buildStats(allTraderTransactions),[allTraderTransactions]);
  const selectTrader=(id:string)=>{setSelectedTraderId(id);setDateFrom("");setDateTo("")};
  return <>
    <style>{`
      .reports-page{--surface:#fff;--surface2:#f8fafc;--text:#17233f;--muted:#667085;--line:#d9dfeb;--accent:#c9a14a;--blue:#2563eb;--shadow:0 16px 38px rgba(15,23,42,.1);width:min(100%,1180px);margin:0 auto;padding:22px 14px 110px;color:var(--text)!important;font-variant-numeric:lining-nums tabular-nums}
      html[data-ghadeer-theme="dark"] .reports-page{--surface:#071a3b;--surface2:#061c40;--text:#fff;--muted:rgba(255,255,255,.66);--line:rgba(35,143,247,.34);--accent:#f0c55f;--blue:#168cff;--shadow:0 18px 42px rgba(0,0,0,.18)}
      .reports-hero{display:flex;justify-content:space-between;gap:18px;align-items:center;padding:26px;border:1px solid var(--line);border-radius:24px;background:var(--surface)!important;box-shadow:var(--shadow)}html[data-ghadeer-theme="dark"] .reports-hero{background:radial-gradient(circle at 12% 20%,rgba(22,140,255,.22),transparent 28%),linear-gradient(145deg,#071f47,#03152f)!important}.reports-hero h1{margin:0 0 7px;font-size:clamp(1.55rem,5vw,2.35rem);color:var(--text)!important}.reports-hero p{margin:0;color:var(--muted)!important;line-height:1.8}.reports-hero-badge{flex:0 0 auto;width:76px;height:76px;display:grid;place-items:center;border-radius:22px;color:var(--accent);border:1px solid var(--line);background:var(--surface2)!important}
      .reports-layout{display:grid;grid-template-columns:310px minmax(0,1fr);gap:18px;margin-top:18px}.reports-panel{border:1px solid var(--line);border-radius:21px;background:var(--surface)!important;box-shadow:var(--shadow);color:var(--text)!important}.reports-sidebar{padding:18px;align-self:start;position:sticky;top:94px}.reports-panel-title{display:flex;align-items:center;gap:10px;margin:0 0 14px;color:var(--text)!important;font-size:1.05rem}.reports-search{position:relative;margin-bottom:13px}.reports-search svg{position:absolute;right:13px;top:50%;transform:translateY(-50%);color:var(--muted)}.reports-search input,.report-filter input{width:100%;margin:0!important;border:1px solid var(--line)!important;border-radius:14px!important;background:var(--surface2)!important;color:var(--text)!important}.reports-search input{padding:11px 42px 11px 12px!important}.report-filter input{padding:10px 12px!important}.trader-list{display:grid;gap:8px;max-height:520px;overflow:auto}.trader-button{width:100%;text-align:right;display:grid;grid-template-columns:42px 1fr;gap:10px;align-items:center;padding:11px;border:1px solid transparent!important;border-radius:15px!important;background:transparent!important;color:var(--text)!important;cursor:pointer}.trader-button:hover{border-color:var(--line)!important;background:var(--surface2)!important}.trader-button.active{border-color:var(--accent)!important;background:var(--surface2)!important}.trader-avatar{width:42px;height:42px;display:grid;place-items:center;border-radius:14px;background:var(--surface2)!important;color:var(--accent)}.trader-copy strong,.trader-copy small{display:block;color:var(--text)!important}.trader-copy small{opacity:.58;margin-top:2px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
      .reports-main{display:grid;gap:18px;min-width:0}.customer-summary{padding:20px}.customer-head{display:flex;justify-content:space-between;align-items:flex-start;gap:15px;margin-bottom:16px}.customer-head h2{margin:0;color:var(--text)!important;font-size:1.35rem}.customer-meta{display:flex;gap:12px;flex-wrap:wrap;margin-top:7px}.customer-meta span{display:inline-flex;align-items:center;gap:6px;color:var(--muted)!important;font-size:.88rem}.period-chip{display:inline-flex;align-items:center;gap:6px;margin-top:10px;padding:7px 10px;border-radius:999px;border:1px solid var(--line);background:var(--surface2)!important;color:var(--accent)!important;font-size:.8rem;font-weight:900}.refresh-report,.clear-filter{display:inline-flex;align-items:center;justify-content:center;gap:7px;padding:9px 12px;border:1px solid var(--line)!important;border-radius:12px!important;background:var(--surface2)!important;color:var(--text)!important;cursor:pointer}.clear-filter.active{background:rgba(240,197,95,.12)!important;border-color:rgba(240,197,95,.45)!important;color:var(--accent)!important}.report-filters{display:grid;grid-template-columns:1fr 1fr auto;gap:10px;align-items:end;padding-top:14px;border-top:1px solid var(--line)}.report-filter label{display:block;margin-bottom:6px;color:var(--text)!important;font-size:.82rem;font-weight:800}
      .report-stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.report-stat{padding:17px;border:1px solid var(--line);border-radius:18px;background:var(--surface)!important;box-shadow:var(--shadow)}.report-stat-top{display:flex;justify-content:space-between;align-items:center;gap:8px;color:var(--muted)!important;font-size:.82rem}.report-stat-icon{width:36px;height:36px;display:grid;place-items:center;border-radius:12px;background:var(--surface2)!important;color:var(--text)}.report-stat.gold .report-stat-icon{color:var(--accent)}.report-stat.green .report-stat-icon{color:#16a34a}.report-stat.red .report-stat-icon{color:#dc2626}.report-stat.blue .report-stat-icon{color:var(--blue)}.report-stat strong{display:block;margin-top:12px;color:var(--text)!important;font-size:clamp(1.02rem,3vw,1.4rem);direction:ltr;text-align:right}.report-stat small{display:block;margin-top:5px;color:var(--muted)!important;font-size:.72rem}
      .account-overview{padding:18px 20px}.account-overview h3{margin:0 0 14px}.overview-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.overview-item{padding:13px;border-radius:15px;border:1px solid var(--line);background:var(--surface2)!important}.overview-item span{display:block;color:var(--muted)!important;font-size:.75rem;margin-bottom:6px}.overview-item strong{display:block;color:var(--text)!important;font-size:.92rem;line-height:1.5}.overview-item strong.ltr{direction:ltr;text-align:right}
      .transactions-panel{overflow:hidden}.transactions-title{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:18px 20px;border-bottom:1px solid var(--line)}.transactions-title h3{margin:0;color:var(--text)!important}.transactions-title span{color:var(--muted)!important;font-size:.86rem}.transactions-table-wrap{overflow:auto}.report-table{width:100%;min-width:760px;border-collapse:collapse;background:transparent!important}.report-table th{padding:12px 14px;text-align:right;color:var(--accent)!important;background:var(--surface2)!important;border-bottom:1px solid var(--line)!important;white-space:nowrap}.report-table td{padding:13px 14px;color:var(--text)!important;border-bottom:1px solid var(--line)!important}.type-badge{display:inline-flex;align-items:center;gap:6px;padding:6px 9px;border-radius:999px;font-weight:800;font-size:.78rem}.type-badge.in,.amount-in{color:#16a34a!important}.type-badge.out,.amount-out{color:#dc2626!important}.amount-in,.amount-out{font-weight:900;direction:ltr}.empty-report{padding:46px 20px;text-align:center;color:var(--muted)!important}.report-error{margin-top:16px;padding:13px 16px;border-radius:14px;color:#b91c1c!important;border:1px solid #fecaca;background:#fef2f2}
      @media(max-width:900px){.reports-layout{grid-template-columns:1fr}.reports-sidebar{position:static}.trader-list{grid-template-columns:repeat(2,minmax(0,1fr));max-height:300px}.report-stats,.overview-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:600px){.reports-page{padding-inline:12px}.reports-hero{padding:21px 18px}.reports-hero-badge{width:62px;height:62px}.trader-list{grid-template-columns:1fr}.customer-head{flex-direction:column}.report-filters{grid-template-columns:1fr 1fr}.clear-filter{grid-column:1/-1}.report-stats{gap:7px}.report-stat{padding:14px 10px}.overview-grid{gap:7px}.account-overview{padding:14px 10px}}
    `}</style>
    <div className="reports-page">
      <section className="reports-hero"><div><h1>تقارير العملاء والحسابات</h1><p>اختر العميل لعرض الحساب الكامل تلقائيًا لكل الفترات، مع إحصائيات وحركات مفصلة.</p></div><div className="reports-hero-badge"><TrendingUp size={36}/></div></section>
      {error?<div className="report-error">{error}</div>:null}
      <div className="reports-layout">
        <aside className="reports-panel reports-sidebar"><h2 className="reports-panel-title"><Users size={20}/> العملاء</h2><div className="reports-search"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="ابحث باسم العميل أو الهاتف"/></div><div className="trader-list">{loading?<div className="empty-report">جارٍ تحميل العملاء...</div>:filteredTraders.length===0?<div className="empty-report">لا يوجد عملاء مطابقون.</div>:filteredTraders.map(t=><button key={t.id} type="button" className={`trader-button${selectedTraderId===t.id?" active":""}`} onClick={()=>selectTrader(t.id)}><span className="trader-avatar"><UserRound size={21}/></span><span className="trader-copy"><strong>{t.name}</strong><small>{t.phone||t.address||"بدون تفاصيل إضافية"}</small></span></button>)}</div></aside>
        <main className="reports-main">
          <section className="reports-panel customer-summary">{selectedTrader?<><div className="customer-head"><div><h2>{selectedTrader.name}</h2><div className="customer-meta">{selectedTrader.phone?<span><Phone size={15}/>{selectedTrader.phone}</span>:null}{selectedTrader.address?<span><UserRound size={15}/>{selectedTrader.address}</span>:null}<span><CalendarDays size={15}/> منذ {formatDate(selectedTrader.created_at)}</span></div><span className="period-chip"><CalendarDays size={14}/>{hasDateFilter?"الفترة المحددة":"جميع الفترات — الحساب الكامل"}</span></div><button type="button" className="refresh-report" onClick={()=>void loadReportData()}><RefreshCcw size={16}/> تحديث</button></div><div className="report-filters"><div className="report-filter"><label>من تاريخ</label><input type="date" value={dateFrom} onChange={e=>setDateFrom(e.target.value)}/></div><div className="report-filter"><label>إلى تاريخ</label><input type="date" value={dateTo} onChange={e=>setDateTo(e.target.value)}/></div><button type="button" className={`clear-filter${!hasDateFilter?" active":""}`} onClick={()=>{setDateFrom("");setDateTo("")}}><Filter size={15}/> جميع الفترات</button></div></>:<div className="empty-report">اختر عميلًا لعرض تفاصيل حسابه.</div>}</section>
          <section className="report-stats"><Stat cls="green" label="إجمالي الداخل" icon={<ArrowDownLeft size={18}/>} value={formatAmount(stats.incoming)} note={`${formatInteger(stats.incomingCount)} حركة`}/><Stat cls="red" label="إجمالي الخارج" icon={<ArrowUpRight size={18}/>} value={formatAmount(stats.outgoing)} note={`${formatInteger(stats.outgoingCount)} حركة`}/><Stat cls="gold" label="الرصيد الحالي" icon={<WalletCards size={18}/>} value={formatAmount(stats.balance)} note={hasDateFilter?"رصيد الفترة":"الرصيد الكلي"}/><Stat label="عدد الحركات" icon={<FileText size={18}/>} value={formatInteger(stats.count)} note={hasDateFilter?"ضمن الفترة":"كل الحركات"}/><Stat cls="blue" label="عدد الوثائق" icon={<FileText size={18}/>} value={formatInteger(stats.documents)} note="وثائق مرتبطة"/><Stat cls="blue" label="متوسط الحركة" icon={<Gauge size={18}/>} value={formatAmount(stats.average)} note="متوسط قيمة الحركة"/><Stat label="أول حركة" icon={<CalendarDays size={18}/>} value={stats.firstDate?formatDate(stats.firstDate):"—"} note="بداية الحساب"/><Stat label="آخر حركة" icon={<CalendarDays size={18}/>} value={stats.lastDate?formatDate(stats.lastDate):"—"} note="آخر تحديث مالي"/></section>
          <section className="reports-panel account-overview"><h3>ملخص الحساب الكلي</h3><div className="overview-grid"><Overview label="إجمالي الداخل لكل الفترات" value={formatAmount(allTimeStats.incoming)}/><Overview label="إجمالي الخارج لكل الفترات" value={formatAmount(allTimeStats.outgoing)}/><Overview label="الرصيد الكلي لكل الفترات" value={formatAmount(allTimeStats.balance)}/><Overview label="إجمالي الحركات لكل الفترات" value={formatInteger(allTimeStats.count)}/></div></section>
          <section className="reports-panel transactions-panel"><div className="transactions-title"><h3>تقرير مفصل عن العميل</h3><span>{formatInteger(traderTransactions.length)} حركة {hasDateFilter?"ضمن الفترة":"في جميع الفترات"}</span></div>{loading?<div className="empty-report">جارٍ تحميل الحركات...</div>:!selectedTrader?<div className="empty-report">اختر عميلًا من القائمة لعرض حسابه.</div>:traderTransactions.length===0?<div className="empty-report">لا توجد حركات لهذا العميل ضمن النطاق المحدد.</div>:<div className="transactions-table-wrap"><table className="report-table"><thead><tr><th>التاريخ</th><th>رقم الوثيقة</th><th>نوع الحركة</th><th>التفاصيل</th><th>السائق / الحمولة</th><th>المبلغ</th></tr></thead><tbody>{traderTransactions.map(t=>{const incoming=isIncoming(t.type);return <tr key={t.id}><td>{formatDateTime(t.created_at)}</td><td>{toEnglishDigits(t.document_number||"—")}</td><td><span className={`type-badge ${incoming?"in":"out"}`}>{incoming?<ArrowDownLeft size={14}/>:<ArrowUpRight size={14}/>} {humanizeType(t.type)}</span></td><td>{toEnglishDigits(t.description||"—")}</td><td>{toEnglishDigits([t.driver_name,t.cargo_typedetails].filter(Boolean).join(" • ")||"—")}</td><td className={incoming?"amount-in":"amount-out"}>{incoming?"+":"-"}{formatAmount(Math.abs(Number(t.amount)||0))}</td></tr>})}</tbody></table></div>}</section>
        </main>
      </div>
    </div>
  </>;
}

function buildStats(items:Transaction[]):ReportStats{let incoming=0,outgoing=0,incomingCount=0,outgoingCount=0;const documents=new Set<string>();for(const t of items){const amount=Math.abs(Number(t.amount)||0);if(isIncoming(t.type)){incoming+=amount;incomingCount++}else{outgoing+=amount;outgoingCount++}if(t.document_id)documents.add(t.document_id);else if(t.document_number)documents.add(t.document_number)}const chronological=[...items].sort((a,b)=>new Date(a.created_at).getTime()-new Date(b.created_at).getTime());return{incoming,outgoing,balance:incoming-outgoing,count:items.length,incomingCount,outgoingCount,documents:documents.size,average:items.length?(incoming+outgoing)/items.length:0,firstDate:chronological[0]?.created_at??null,lastDate:chronological[chronological.length-1]?.created_at??null}}
function Stat({cls="",label,icon,value,note}:{cls?:string;label:string;icon:ReactNode;value:string;note?:string}){return <div className={`report-stat ${cls}`}><div className="report-stat-top"><span>{label}</span><span className="report-stat-icon">{icon}</span></div><strong>{value}</strong>{note?<small>{note}</small>:null}</div>}
function Overview({label,value}:{label:string;value:string}){return <div className="overview-item"><span>{label}</span><strong className="ltr">{value}</strong></div>}
function isIncoming(type:string){const n=(type||"").trim().toLowerCase();return ["credit","income","payment","receipt","deposit","قبض","دائن","وارد","ايداع","إيداع"].some(x=>n.includes(x))}
function humanizeType(type:string){const n=(type||"").trim().toLowerCase();if(["credit","income","payment","receipt","deposit"].some(x=>n.includes(x)))return"داخل";if(["debit","expense","withdraw","payment_out"].some(x=>n.includes(x)))return"خارج";return type||"حركة"}
function formatAmount(value:number){return new Intl.NumberFormat("en-US",{maximumFractionDigits:2}).format(value||0)}
function formatInteger(value:number){return new Intl.NumberFormat("en-US",{maximumFractionDigits:0}).format(value||0)}
function formatDate(value:string){return new Intl.DateTimeFormat("en-GB",{year:"numeric",month:"short",day:"2-digit"}).format(new Date(value))}
function formatDateTime(value:string){return new Intl.DateTimeFormat("en-GB",{year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date(value))}
function toEnglishDigits(value:string){return value.replace(/[٠-٩]/g,d=>String("٠١٢٣٤٥٦٧٨٩".indexOf(d))).replace(/[۰-۹]/g,d=>String("۰۱۲۳۴۵۶۷۸۹".indexOf(d)))}
