/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedCompaniesRouteImport } from './routes/_authenticated/companies'
import { Route as AuthenticatedDocumentsNewRouteImport } from './routes/_authenticated/documents.new'
import { Route as AuthenticatedDocumentsIdRouteImport } from './routes/_authenticated/documents.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompaniesRoute = AuthenticatedCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsNewRoute =
  AuthenticatedDocumentsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedDocumentsRoute,
  } as any)
const AuthenticatedDocumentsIdRoute =
  AuthenticatedDocumentsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedDocumentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/companies': typeof AuthenticatedCompaniesRoute
  '/documents': typeof AuthenticatedDocumentsRouteWithChildren
  '/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/documents/new': typeof AuthenticatedDocumentsNewRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/companies': typeof AuthenticatedCompaniesRoute
  '/documents': typeof AuthenticatedDocumentsRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/documents/new': typeof AuthenticatedDocumentsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/companies': typeof AuthenticatedCompaniesRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/_authenticated/documents/new': typeof AuthenticatedDocumentsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/companies'
    | '/documents'
    | '/documents/$id'
    | '/documents/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/companies'
    | '/documents'
    | '/'
    | '/documents/$id'
    | '/documents/new'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/companies'
    | '/_authenticated/documents'
    | '/_authenticated/'
    | '/_authenticated/documents/$id'
    | '/_authenticated/documents/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/companies': {
      id: '/_authenticated/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AuthenticatedCompaniesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/new': {
      id: '/_authenticated/documents/new'
      path: '/new'
      fullPath: '/documents/new'
      preLoaderRoute: typeof AuthenticatedDocumentsNewRouteImport
      parentRoute: typeof AuthenticatedDocumentsRoute
    }
    '/_authenticated/documents/$id': {
      id: '/_authenticated/documents/$id'
      path: '/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof AuthenticatedDocumentsIdRouteImport
      parentRoute: typeof AuthenticatedDocumentsRoute
    }
  }
}

interface AuthenticatedDocumentsRouteChildren {
  AuthenticatedDocumentsIdRoute: typeof AuthenticatedDocumentsIdRoute
  AuthenticatedDocumentsNewRoute: typeof AuthenticatedDocumentsNewRoute
}

const AuthenticatedDocumentsRouteChildren: AuthenticatedDocumentsRouteChildren =
  {
    AuthenticatedDocumentsIdRoute: AuthenticatedDocumentsIdRoute,
    AuthenticatedDocumentsNewRoute: AuthenticatedDocumentsNewRoute,
  }

const AuthenticatedDocumentsRouteWithChildren =
  AuthenticatedDocumentsRoute._addFileChildren(
    AuthenticatedDocumentsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCompaniesRoute: typeof AuthenticatedCompaniesRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCompaniesRoute: AuthenticatedCompaniesRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
